import { render } from 'preact'
import './index.css'
import { App } from './app.tsx'
// Registers the auto-updating service worker (generated by vite-plugin-pwa).
// With registerType:'autoUpdate' a new deploy is fetched and activated in the
// background; the virtual module is a no-op in dev (devOptions.enabled=false).
import { registerSW } from 'virtual:pwa-register'
registerSW({ immediate: true })

render(<App />, document.getElementById('app')!)
